namespace StudentInfoById.Models
{
    public class StudentInfoModel
    {
        public string ODataContext { get; set; }
        public int Id { get; set; }
        public string AcgEligReasonCode { get; set; }
        public int AgencyId { get; set; }
        public string AlienNumber { get; set; }
        public string ArAccountStatus { get; set; }
        public decimal ArBalance { get; set; }
        public int ArNextTransactionNumber { get; set; }
        public int AssignedAdmissionsRepId { get; set; }
        public string AthleticIdentifier { get; set; }
        public string BestTimeToContact { get; set; }
        public int CampusId { get; set; }
        public int CitizenId { get; set; }
        public string City { get; set; }
        public int? CollegeId { get; set; }
        public int CountryId { get; set; }
        public int CountyId { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public decimal CumulativeGpa { get; set; }
        public decimal CumulativeGpaPoints { get; set; }
        public int? CurrencyCodeId { get; set; }
        public DateTime CurrentLda { get; set; }
        public bool DataBlockIndicator { get; set; }
        public DateTime DateOfBirth { get; set; }
        public DateTime? DbiModifiedDate { get; set; }
        public int? DefaultAddressCode { get; set; }
        public int? DefaultMasterStudentAddressId { get; set; }
        public int? DefaultStudentAddressId { get; set; }
        public string Disabled { get; set; }
        public string DriverLicenseNumber { get; set; }
        public string DriverLicenseState { get; set; }
        public string EmailAddress { get; set; }
        public string EmployabilityAboutInfo { get; set; }
        public int EmployerId { get; set; }
        public int EmploymentStatusId { get; set; }
        public string ExternalStudentIdentifier { get; set; }
        public int ExtraCurricularActivityId { get; set; }
        public string FacebookUrl { get; set; }
        public DateTime? FaGradPlusCounselingDate { get; set; }
        public int? FaRigorousHighSchoolProgramCodeId { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public int GenderId { get; set; }
        public decimal GpaCredits { get; set; }
        public bool? HispanicLatino { get; set; }
        public decimal? HsAcademicGpa { get; set; }
        public string InstagramUrl { get; set; }
        public bool IsActive { get; set; }
        public bool? IsAllowedBulkRegistrationByTrack { get; set; }
        public bool IsBadAddress { get; set; }
        public bool IsBadPhone { get; set; }
        public bool IsDdVeteran { get; set; }
        public bool IsEftDefaultForStipends { get; set; }
        public bool IsExcludedCrmIntegration { get; set; }
        public bool IsInDistrict { get; set; }
        public bool IsSscrError11Received { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public string LastFourSsn { get; set; }
        public DateTime? LastInterestDate { get; set; }
        public DateTime LastModifiedDateTime { get; set; }
        public int LastModifiedUserId { get; set; }
        public string LastName { get; set; }
        public string LastNameFirstFour { get; set; }
        public DateTime? LastStatementBeginDate { get; set; }
        public DateTime? LastStatementCloseDate { get; set; }
        public DateTime? LastStatementDate { get; set; }
        public DateTime LeadDate { get; set; }
        public int LeadSourceId { get; set; }
        public int LeadTypeId { get; set; }
        public string LinkedInUrl { get; set; }
        public string MaidenName { get; set; }
        public int MaritalStatusId { get; set; }
        public string Mi { get; set; }
        public string MiddleName { get; set; }
        public string MobilePhoneNumber { get; set; }
        public int NationalityId { get; set; }
        public string NickName { get; set; }
        public bool NiStudent { get; set; }
        public string Note { get; set; }
        public int OriginalAssignedAdmissionsRepId { get; set; }
        public DateTime OriginalExpectedStartDate { get; set; }
        public DateTime OriginalStartDate { get; set; }
        public string OtherEmailAddress { get; set; }
        public string OtherPhoneNumber { get; set; }
        public int PersonId { get; set; }
        public string PhoneNumber { get; set; }
        public int Pin { get; set; }
        public string PostalCode { get; set; }
        public string PostalCodeFirstThree { get; set; }
        public string PreferredContactType { get; set; }
        public string PreferredName { get; set; }
        public decimal? PreviousEducationGpa { get; set; }
        public int PreviousEducationId { get; set; }
        public int ProgramGroupId { get; set; }
        public int ProgramId { get; set; }
        public string RawFirstName { get; set; }
        public string RawLastName { get; set; }
        public string RawPhoneNumber { get; set; }
        public int SchoolStatusId { get; set; }
        public int ShiftId { get; set; }
        public int? SmsServiceProviderId { get; set; }
        public string SourceSystem { get; set; }
        public string Ssn { get; set; }
        public DateTime StartDate { get; set; }
        public string State { get; set; }
        public string StatementComment { get; set; }
        public string StreetAddress { get; set; }
        public string StreetAddress2 { get; set; }
        public string StudentFullName { get; set; }
        public string StudentIdentifier { get; set; }
        public string StudentNumber { get; set; }
        public bool SubscribeToSms { get; set; }
        public string Suffix { get; set; }
        public int? SuffixId { get; set; }
        public int TitleId { get; set; }
        public string TwitterUrl { get; set; }
        public string Veteran { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string WorkPhoneNumberExtension { get; set; }
    }

}
